# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body74 Model.
  class Body74 < BaseModel
    # The unique identifier for the voice call.
    # @return [String]
    attr_accessor :call_sid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['call_sid'] = 'callSid'
      @_hash
    end

    def initialize(call_sid = nil)
      @call_sid = call_sid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      call_sid = hash['callSid']

      # Create object from extracted values.
      Body74.new(call_sid)
    end
  end
end
