# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body46 Model.
  class Body46 < BaseModel
    # The unique identifier for the voice call.
    # @return [String]
    attr_accessor :callsid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['callsid'] = 'callsid'
      @_hash
    end

    def initialize(callsid = nil)
      @callsid = callsid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      callsid = hash['callsid']

      # Create object from extracted values.
      Body46.new(callsid)
    end
  end
end
