# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body72 Model.
  class Body72 < BaseModel
    # Specifies the multiple phone numbers for check updated spamscore .
    # @return [String]
    attr_accessor :phonenumber

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phonenumber'] = 'Phonenumber'
      @_hash
    end

    def initialize(phonenumber = nil)
      @phonenumber = phonenumber
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phonenumber = hash['Phonenumber']

      # Create object from extracted values.
      Body72.new(phonenumber)
    end
  end
end
