# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body30 Model.
  class Body30 < BaseModel
    # The email address to be remove from the bounced email list.
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['email'] = 'Email'
      @_hash
    end

    def initialize(email = nil)
      @email = email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash['Email']

      # Create object from extracted values.
      Body30.new(email)
    end
  end
end
