# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body20 Model.
  class Body20 < BaseModel
    # The unique identifier of each conference resource
    # @return [String]
    attr_accessor :conference_sid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['conference_sid'] = 'ConferenceSid'
      @_hash
    end

    def initialize(conference_sid = nil)
      @conference_sid = conference_sid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      conference_sid = hash['ConferenceSid']

      # Create object from extracted values.
      Body20.new(conference_sid)
    end
  end
end
