# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body11 Model.
  class Body11 < BaseModel
    # URL pointing to the location of the audio file that is to be transcribed.
    # @return [String]
    attr_accessor :audiourl

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['audiourl'] = 'audiourl'
      @_hash
    end

    def initialize(audiourl = nil)
      @audiourl = audiourl
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      audiourl = hash['audiourl']

      # Create object from extracted values.
      Body11.new(audiourl)
    end
  end
end
