# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body76 Model.
  class Body76 < BaseModel
    # Only list Short Code Assignment sent from this Short Code
    # @return [String]
    attr_accessor :shortcode

    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [String]
    attr_accessor :page

    # The count of objects to return per page.
    # @return [String]
    attr_accessor :pagesize

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['shortcode'] = 'Shortcode'
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash
    end

    def initialize(shortcode = nil,
                   page = nil,
                   pagesize = nil)
      @shortcode = shortcode
      @page = page
      @pagesize = pagesize
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      shortcode = hash['Shortcode']
      page = hash['page']
      pagesize = hash['pagesize']

      # Create object from extracted values.
      Body76.new(shortcode,
                 page,
                 pagesize)
    end
  end
end
