# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body43 Model.
  class Body43 < BaseModel
    # A valid Ytel Voice enabled number (E.164 format) that will be initiating
    # the phone call.
    # @return [String]
    attr_accessor :from

    # A required secondary Caller ID for RVM to work.
    # @return [String]
    attr_accessor :rvm_caller_id

    # A valid number (E.164 format) that will receive the phone call.
    # @return [String]
    attr_accessor :to

    # The URL requested once the RVM connects. A set of default parameters will
    # be sent here.
    # @return [String]
    attr_accessor :voice_mail_url

    # Specifies the HTTP method used to request the required URL once call
    # connects.
    # @return [String]
    attr_accessor :method

    # URL that can be requested to receive notification when call has ended. A
    # set of default parameters will be sent here once the call is finished.
    # @return [String]
    attr_accessor :status_call_back_url

    # Specifies the HTTP method used to request the required StatusCallBackUrl
    # once call connects.
    # @return [String]
    attr_accessor :stats_call_back_method

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['from'] = 'From'
      @_hash['rvm_caller_id'] = 'RVMCallerId'
      @_hash['to'] = 'To'
      @_hash['voice_mail_url'] = 'VoiceMailURL'
      @_hash['method'] = 'Method'
      @_hash['status_call_back_url'] = 'StatusCallBackUrl'
      @_hash['stats_call_back_method'] = 'StatsCallBackMethod'
      @_hash
    end

    def initialize(from = nil,
                   rvm_caller_id = nil,
                   to = nil,
                   voice_mail_url = nil,
                   method = nil,
                   status_call_back_url = nil,
                   stats_call_back_method = nil)
      @from = from
      @rvm_caller_id = rvm_caller_id
      @to = to
      @voice_mail_url = voice_mail_url
      @method = method
      @status_call_back_url = status_call_back_url
      @stats_call_back_method = stats_call_back_method
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      from = hash['From']
      rvm_caller_id = hash['RVMCallerId']
      to = hash['To']
      voice_mail_url = hash['VoiceMailURL']
      method = hash['Method']
      status_call_back_url = hash['StatusCallBackUrl']
      stats_call_back_method = hash['StatsCallBackMethod']

      # Create object from extracted values.
      Body43.new(from,
                 rvm_caller_id,
                 to,
                 voice_mail_url,
                 method,
                 status_call_back_url,
                 stats_call_back_method)
    end
  end
end
