# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body36 Model.
  class Body36 < BaseModel
    # Filter account information based on date.
    # @return [String]
    attr_accessor :date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['date'] = 'Date'
      @_hash
    end

    def initialize(date = nil)
      @date = date
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      date = hash['Date']

      # Create object from extracted values.
      Body36.new(date)
    end
  end
end
