# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body28 Model.
  class Body28 < BaseModel
    # The unique identifier for voice call that is in progress.
    # @return [String]
    attr_accessor :call_sid

    # URL the in-progress call will be redirected to
    # @return [String]
    attr_accessor :url

    # The method used to request the above Url parameter
    # @return [String]
    attr_accessor :method

    # Status to set the in-progress call to
    # @return [Status1Enum]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['call_sid'] = 'CallSid'
      @_hash['url'] = 'Url'
      @_hash['method'] = 'Method'
      @_hash['status'] = 'Status'
      @_hash
    end

    def initialize(call_sid = nil,
                   url = nil,
                   method = nil,
                   status = nil)
      @call_sid = call_sid
      @url = url
      @method = method
      @status = status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      call_sid = hash['CallSid']
      url = hash['Url']
      method = hash['Method']
      status = hash['Status']

      # Create object from extracted values.
      Body28.new(call_sid,
                 url,
                 method,
                 status)
    end
  end
end
