# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body49 Model.
  class Body49 < BaseModel
    # Filter usage results by product type.
    # @return [ProductCodeEnum]
    attr_accessor :product_code

    # Filter usage objects by start date.
    # @return [String]
    attr_accessor :start_date

    # Filter usage objects by end date.
    # @return [String]
    attr_accessor :end_date

    # Will include all subaccount usage data
    # @return [String]
    attr_accessor :include_sub_accounts

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_code'] = 'ProductCode'
      @_hash['start_date'] = 'startDate'
      @_hash['end_date'] = 'endDate'
      @_hash['include_sub_accounts'] = 'IncludeSubAccounts'
      @_hash
    end

    def initialize(product_code = nil,
                   start_date = nil,
                   end_date = nil,
                   include_sub_accounts = nil)
      @product_code = product_code
      @start_date = start_date
      @end_date = end_date
      @include_sub_accounts = include_sub_accounts
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_code = hash['ProductCode']
      start_date = hash['startDate']
      end_date = hash['endDate']
      include_sub_accounts = hash['IncludeSubAccounts']

      # Create object from extracted values.
      Body49.new(product_code,
                 start_date,
                 end_date,
                 include_sub_accounts)
    end
  end
end
