# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body6 Model.
  class Body6 < BaseModel
    # ID of the active conference
    # @return [String]
    attr_accessor :conference_sid

    # ID of an active participant
    # @return [String]
    attr_accessor :participant_sid

    # Mute a participant
    # @return [Boolean]
    attr_accessor :muted

    # Make it so a participant cant hear
    # @return [Boolean]
    attr_accessor :deaf

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['conference_sid'] = 'conferenceSid'
      @_hash['participant_sid'] = 'ParticipantSid'
      @_hash['muted'] = 'Muted'
      @_hash['deaf'] = 'Deaf'
      @_hash
    end

    def initialize(conference_sid = nil,
                   participant_sid = nil,
                   muted = nil,
                   deaf = nil)
      @conference_sid = conference_sid
      @participant_sid = participant_sid
      @muted = muted
      @deaf = deaf
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      conference_sid = hash['conferenceSid']
      participant_sid = hash['ParticipantSid']
      muted = hash['Muted']
      deaf = hash['Deaf']

      # Create object from extracted values.
      Body6.new(conference_sid,
                participant_sid,
                muted,
                deaf)
    end
  end
end
