# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body68 Model.
  class Body68 < BaseModel
    # Sub account user first name
    # @return [String]
    attr_accessor :first_name

    # sub account user last name
    # @return [String]
    attr_accessor :last_name

    # Sub account email address
    # @return [String]
    attr_accessor :email

    # Descriptive name of the sub account
    # @return [String]
    attr_accessor :friendly_name

    # The password of the sub account.  Please make sure to make as password
    # that is at least 8 characters long, contain a symbol, uppercase and a
    # number.
    # @return [String]
    attr_accessor :password

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_name'] = 'FirstName'
      @_hash['last_name'] = 'LastName'
      @_hash['email'] = 'Email'
      @_hash['friendly_name'] = 'FriendlyName'
      @_hash['password'] = 'Password'
      @_hash
    end

    def initialize(first_name = nil,
                   last_name = nil,
                   email = nil,
                   friendly_name = nil,
                   password = nil)
      @first_name = first_name
      @last_name = last_name
      @email = email
      @friendly_name = friendly_name
      @password = password
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first_name = hash['FirstName']
      last_name = hash['LastName']
      email = hash['Email']
      friendly_name = hash['FriendlyName']
      password = hash['Password']

      # Create object from extracted values.
      Body68.new(first_name,
                 last_name,
                 email,
                 friendly_name,
                 password)
    end
  end
end
