# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body4 Model.
  class Body4 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # The count of objects to return per page.
    # @return [Integer]
    attr_accessor :page_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'Page'
      @_hash['page_size'] = 'PageSize'
      @_hash
    end

    def initialize(page = nil,
                   page_size = nil)
      @page = page
      @page_size = page_size
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['Page']
      page_size = hash['PageSize']

      # Create object from extracted values.
      Body4.new(page,
                page_size)
    end
  end
end
