# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body32 Model.
  class Body32 < BaseModel
    # The starting point of the list of spam emails that should be returned.
    # @return [String]
    attr_accessor :offset

    # The count of results that should be returned.
    # @return [String]
    attr_accessor :limit

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['offset'] = 'Offset'
      @_hash['limit'] = 'Limit'
      @_hash
    end

    def initialize(offset = nil,
                   limit = nil)
      @offset = offset
      @limit = limit
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      offset = hash['Offset']
      limit = hash['Limit']

      # Create object from extracted values.
      Body32.new(offset,
                 limit)
    end
  end
end
