# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body35 Model.
  class Body35 < BaseModel
    # The SubaccountSid to be activated or suspended
    # @return [String]
    attr_accessor :sub_account_sid

    # 0 to suspend or 1 to activate
    # @return [ActivateEnum]
    attr_accessor :activate

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sub_account_sid'] = 'SubAccountSID'
      @_hash['activate'] = 'Activate'
      @_hash
    end

    def initialize(sub_account_sid = nil,
                   activate = nil)
      @sub_account_sid = sub_account_sid
      @activate = activate
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sub_account_sid = hash['SubAccountSID']
      activate = hash['Activate']

      # Create object from extracted values.
      Body35.new(sub_account_sid,
                 activate)
    end
  end
end
