# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body23 Model.
  class Body23 < BaseModel
    # The unique identifier of each call resource
    # @return [String]
    attr_accessor :call_sid

    # Set true to initiate recording or false to terminate recording
    # @return [Boolean]
    attr_accessor :record

    # The leg of the call to record
    # @return [DirectionEnum]
    attr_accessor :direction

    # Time in seconds the recording duration should not exceed
    # @return [Integer]
    attr_accessor :time_limit

    # URL consulted after the recording completes
    # @return [String]
    attr_accessor :call_back_url

    # Format of the recording file. Can be .mp3 or .wav
    # @return [FileformatEnum]
    attr_accessor :fileformat

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['call_sid'] = 'CallSid'
      @_hash['record'] = 'Record'
      @_hash['direction'] = 'Direction'
      @_hash['time_limit'] = 'TimeLimit'
      @_hash['call_back_url'] = 'CallBackUrl'
      @_hash['fileformat'] = 'Fileformat'
      @_hash
    end

    def initialize(call_sid = nil,
                   record = nil,
                   direction = nil,
                   time_limit = nil,
                   call_back_url = nil,
                   fileformat = nil)
      @call_sid = call_sid
      @record = record
      @direction = direction
      @time_limit = time_limit
      @call_back_url = call_back_url
      @fileformat = fileformat
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      call_sid = hash['CallSid']
      record = hash['Record']
      direction = hash['Direction']
      time_limit = hash['TimeLimit']
      call_back_url = hash['CallBackUrl']
      fileformat = hash['Fileformat']

      # Create object from extracted values.
      Body23.new(call_sid,
                 record,
                 direction,
                 time_limit,
                 call_back_url,
                 fileformat)
    end
  end
end
