# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body51 Model.
  class Body51 < BaseModel
    # The unique identifier for a conference object.
    # @return [String]
    attr_accessor :conference_sid

    # The phone number of the participant to be added.
    # @return [String]
    attr_accessor :participant_number

    # Specifies if participant should be muted.
    # @return [Boolean]
    attr_accessor :muted

    # Specifies if the participant should hear audio in the conference.
    # @return [Boolean]
    attr_accessor :deaf

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['conference_sid'] = 'ConferenceSid'
      @_hash['participant_number'] = 'ParticipantNumber'
      @_hash['muted'] = 'Muted'
      @_hash['deaf'] = 'Deaf'
      @_hash
    end

    def initialize(conference_sid = nil,
                   participant_number = nil,
                   muted = nil,
                   deaf = nil)
      @conference_sid = conference_sid
      @participant_number = participant_number
      @muted = muted
      @deaf = deaf
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      conference_sid = hash['ConferenceSid']
      participant_number = hash['ParticipantNumber']
      muted = hash['Muted']
      deaf = hash['Deaf']

      # Create object from extracted values.
      Body51.new(conference_sid,
                 participant_number,
                 muted,
                 deaf)
    end
  end
end
