# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body39 Model.
  class Body39 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # Number of individual resources listed in the response per page
    # @return [Integer]
    attr_accessor :pagesize

    # From Number to Inbound ShortCode
    # @return [String]
    attr_accessor :from

    # Only list messages sent to this Short Code
    # @return [String]
    attr_accessor :shortcode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['from'] = 'from'
      @_hash['shortcode'] = 'Shortcode'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil,
                   from = nil,
                   shortcode = nil)
      @page = page
      @pagesize = pagesize
      @from = from
      @shortcode = shortcode
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']
      from = hash['from']
      shortcode = hash['Shortcode']

      # Create object from extracted values.
      Body39.new(page,
                 pagesize,
                 from,
                 shortcode)
    end
  end
end
