# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body27 Model.
  class Body27 < BaseModel
    # The unique identifier of each call resource
    # @return [String]
    attr_accessor :call_sid

    # DTMF digits to play to the call. 0-9, #, *, W, or w
    # @return [String]
    attr_accessor :play_dtmf

    # The leg of the call DTMF digits should be sent to
    # @return [PlayDtmfDirectionEnum]
    attr_accessor :play_dtmf_direction

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['call_sid'] = 'CallSid'
      @_hash['play_dtmf'] = 'PlayDtmf'
      @_hash['play_dtmf_direction'] = 'PlayDtmfDirection'
      @_hash
    end

    def initialize(call_sid = nil,
                   play_dtmf = nil,
                   play_dtmf_direction = nil)
      @call_sid = call_sid
      @play_dtmf = play_dtmf
      @play_dtmf_direction = play_dtmf_direction
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      call_sid = hash['CallSid']
      play_dtmf = hash['PlayDtmf']
      play_dtmf_direction = hash['PlayDtmfDirection']

      # Create object from extracted values.
      Body27.new(call_sid,
                 play_dtmf,
                 play_dtmf_direction)
    end
  end
end
