# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body60 Model.
  class Body60 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # Number of individual resources listed in the response per page
    # @return [Integer]
    attr_accessor :pagesize

    # Only list keywords of keyword
    # @return [String]
    attr_accessor :keyword

    # Only list keywords of shortcode
    # @return [Integer]
    attr_accessor :shortcode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['keyword'] = 'Keyword'
      @_hash['shortcode'] = 'Shortcode'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil,
                   keyword = nil,
                   shortcode = nil)
      @page = page
      @pagesize = pagesize
      @keyword = keyword
      @shortcode = shortcode
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']
      keyword = hash['Keyword']
      shortcode = hash['Shortcode']

      # Create object from extracted values.
      Body60.new(page,
                 pagesize,
                 keyword,
                 shortcode)
    end
  end
end
