# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body66 Model.
  class Body66 < BaseModel
    # A valid 10-digit Ytel number (E.164 format).
    # @return [String]
    attr_accessor :phonenumber

    # A specific Accountsid from where Number is getting transfer.
    # @return [String]
    attr_accessor :fromaccountsid

    # A specific Accountsid to which Number is getting transfer.
    # @return [String]
    attr_accessor :toaccountsid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phonenumber'] = 'phonenumber'
      @_hash['fromaccountsid'] = 'fromaccountsid'
      @_hash['toaccountsid'] = 'toaccountsid'
      @_hash
    end

    def initialize(phonenumber = nil,
                   fromaccountsid = nil,
                   toaccountsid = nil)
      @phonenumber = phonenumber
      @fromaccountsid = fromaccountsid
      @toaccountsid = toaccountsid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phonenumber = hash['phonenumber']
      fromaccountsid = hash['fromaccountsid']
      toaccountsid = hash['toaccountsid']

      # Create object from extracted values.
      Body66.new(phonenumber,
                 fromaccountsid,
                 toaccountsid)
    end
  end
end
