# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body58 Model.
  class Body58 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # Number of individual resources listed in the response per page
    # @return [Integer]
    attr_accessor :pagesize

    # Only list SMS messages sent from this number
    # @return [String]
    attr_accessor :from

    # Only list SMS messages sent to Shortcode
    # @return [String]
    attr_accessor :shortcode

    # Only list SMS messages sent in the specified date MAKE REQUEST
    # @return [String]
    attr_accessor :datecreated

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['from'] = 'From'
      @_hash['shortcode'] = 'Shortcode'
      @_hash['datecreated'] = 'Datecreated'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil,
                   from = nil,
                   shortcode = nil,
                   datecreated = nil)
      @page = page
      @pagesize = pagesize
      @from = from
      @shortcode = shortcode
      @datecreated = datecreated
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']
      from = hash['From']
      shortcode = hash['Shortcode']
      datecreated = hash['Datecreated']

      # Create object from extracted values.
      Body58.new(page,
                 pagesize,
                 from,
                 shortcode,
                 datecreated)
    end
  end
end
