# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body13 Model.
  class Body13 < BaseModel
    # The unique identifier for a recording.
    # @return [String]
    attr_accessor :recordingsid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['recordingsid'] = 'recordingsid'
      @_hash
    end

    def initialize(recordingsid = nil)
      @recordingsid = recordingsid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      recordingsid = hash['recordingsid']

      # Create object from extracted values.
      Body13.new(recordingsid)
    end
  end
end
