# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body65 Model.
  class Body65 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # Number of individual resources listed in the response per page
    # @return [Integer]
    attr_accessor :pagesize

    # Only return conferences with the specified FriendlyName
    # @return [String]
    attr_accessor :friendly_name

    # Conference created date
    # @return [String]
    attr_accessor :date_created

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['friendly_name'] = 'FriendlyName'
      @_hash['date_created'] = 'DateCreated'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil,
                   friendly_name = nil,
                   date_created = nil)
      @page = page
      @pagesize = pagesize
      @friendly_name = friendly_name
      @date_created = date_created
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']
      friendly_name = hash['FriendlyName']
      date_created = hash['DateCreated']

      # Create object from extracted values.
      Body65.new(page,
                 pagesize,
                 friendly_name,
                 date_created)
    end
  end
end
