# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body47 Model.
  class Body47 < BaseModel
    # A valid Ytel number (E.164 format).
    # @return [String]
    attr_accessor :phone_number

    # URL requested once the call connects
    # @return [String]
    attr_accessor :voice_url

    # Phone number friendly name description
    # @return [String]
    attr_accessor :friendly_name

    # Post or Get
    # @return [String]
    attr_accessor :voice_method

    # URL requested if the voice URL is not available
    # @return [String]
    attr_accessor :voice_fallback_url

    # Post or Get
    # @return [String]
    attr_accessor :voice_fallback_method

    # callback url after a hangup occurs
    # @return [String]
    attr_accessor :hangup_callback

    # Post or Get
    # @return [String]
    attr_accessor :hangup_callback_method

    # URL requested once the call connects
    # @return [String]
    attr_accessor :heartbeat_url

    # URL that can be requested every 60 seconds during the call to notify of
    # elapsed time
    # @return [String]
    attr_accessor :heartbeat_method

    # URL requested when an SMS is received
    # @return [String]
    attr_accessor :sms_url

    # Post or Get
    # @return [String]
    attr_accessor :sms_method

    # URL used if any errors occur during execution of InboundXML from an SMS or
    # at initial request of the SmsUrl.
    # @return [String]
    attr_accessor :sms_fallback_url

    # The HTTP method Ytel will use when URL requested if the SmsUrl is not
    # available.
    # @return [String]
    attr_accessor :sms_fallback_method

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phone_number'] = 'PhoneNumber'
      @_hash['voice_url'] = 'VoiceUrl'
      @_hash['friendly_name'] = 'FriendlyName'
      @_hash['voice_method'] = 'VoiceMethod'
      @_hash['voice_fallback_url'] = 'VoiceFallbackUrl'
      @_hash['voice_fallback_method'] = 'VoiceFallbackMethod'
      @_hash['hangup_callback'] = 'HangupCallback'
      @_hash['hangup_callback_method'] = 'HangupCallbackMethod'
      @_hash['heartbeat_url'] = 'HeartbeatUrl'
      @_hash['heartbeat_method'] = 'HeartbeatMethod'
      @_hash['sms_url'] = 'SmsUrl'
      @_hash['sms_method'] = 'SmsMethod'
      @_hash['sms_fallback_url'] = 'SmsFallbackUrl'
      @_hash['sms_fallback_method'] = 'SmsFallbackMethod'
      @_hash
    end

    def initialize(phone_number = nil,
                   voice_url = nil,
                   friendly_name = nil,
                   voice_method = nil,
                   voice_fallback_url = nil,
                   voice_fallback_method = nil,
                   hangup_callback = nil,
                   hangup_callback_method = nil,
                   heartbeat_url = nil,
                   heartbeat_method = nil,
                   sms_url = nil,
                   sms_method = nil,
                   sms_fallback_url = nil,
                   sms_fallback_method = nil)
      @phone_number = phone_number
      @voice_url = voice_url
      @friendly_name = friendly_name
      @voice_method = voice_method
      @voice_fallback_url = voice_fallback_url
      @voice_fallback_method = voice_fallback_method
      @hangup_callback = hangup_callback
      @hangup_callback_method = hangup_callback_method
      @heartbeat_url = heartbeat_url
      @heartbeat_method = heartbeat_method
      @sms_url = sms_url
      @sms_method = sms_method
      @sms_fallback_url = sms_fallback_url
      @sms_fallback_method = sms_fallback_method
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phone_number = hash['PhoneNumber']
      voice_url = hash['VoiceUrl']
      friendly_name = hash['FriendlyName']
      voice_method = hash['VoiceMethod']
      voice_fallback_url = hash['VoiceFallbackUrl']
      voice_fallback_method = hash['VoiceFallbackMethod']
      hangup_callback = hash['HangupCallback']
      hangup_callback_method = hash['HangupCallbackMethod']
      heartbeat_url = hash['HeartbeatUrl']
      heartbeat_method = hash['HeartbeatMethod']
      sms_url = hash['SmsUrl']
      sms_method = hash['SmsMethod']
      sms_fallback_url = hash['SmsFallbackUrl']
      sms_fallback_method = hash['SmsFallbackMethod']

      # Create object from extracted values.
      Body47.new(phone_number,
                 voice_url,
                 friendly_name,
                 voice_method,
                 voice_fallback_url,
                 voice_fallback_method,
                 hangup_callback,
                 hangup_callback_method,
                 heartbeat_url,
                 heartbeat_method,
                 sms_url,
                 sms_method,
                 sms_fallback_url,
                 sms_fallback_method)
    end
  end
end
