# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body48 Model.
  class Body48 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # The count of objects to return per page.
    # @return [Integer]
    attr_accessor :pagesize

    # Filter results by creation date
    # @return [String]
    attr_accessor :datecreated

    # The unique identifier for a call.
    # @return [String]
    attr_accessor :callsid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['datecreated'] = 'Datecreated'
      @_hash['callsid'] = 'callsid'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil,
                   datecreated = nil,
                   callsid = nil)
      @page = page
      @pagesize = pagesize
      @datecreated = datecreated
      @callsid = callsid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']
      datecreated = hash['Datecreated']
      callsid = hash['callsid']

      # Create object from extracted values.
      Body48.new(page,
                 pagesize,
                 datecreated,
                 callsid)
    end
  end
end
