# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body9 Model.
  class Body9 < BaseModel
    # The unique identifier for a transcription object.
    # @return [String]
    attr_accessor :transcriptionsid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transcriptionsid'] = 'transcriptionsid'
      @_hash
    end

    def initialize(transcriptionsid = nil)
      @transcriptionsid = transcriptionsid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      transcriptionsid = hash['transcriptionsid']

      # Create object from extracted values.
      Body9.new(transcriptionsid)
    end
  end
end
