# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body73 Model.
  class Body73 < BaseModel
    # The capability the number supports.
    # @return [NumberType2Enum]
    attr_accessor :number_type

    # Specifies the area code for the returned list of available numbers. Only
    # available for North American numbers.
    # @return [String]
    attr_accessor :area_code

    # A positive integer that tells how many number you want to buy at a time.
    # @return [String]
    attr_accessor :quantity

    # If desired quantity is unavailable purchase what is available .
    # @return [String]
    attr_accessor :leftover

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number_type'] = 'NumberType'
      @_hash['area_code'] = 'AreaCode'
      @_hash['quantity'] = 'Quantity'
      @_hash['leftover'] = 'Leftover'
      @_hash
    end

    def initialize(number_type = nil,
                   area_code = nil,
                   quantity = nil,
                   leftover = nil)
      @number_type = number_type
      @area_code = area_code
      @quantity = quantity
      @leftover = leftover
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number_type = hash['NumberType']
      area_code = hash['AreaCode']
      quantity = hash['Quantity']
      leftover = hash['Leftover']

      # Create object from extracted values.
      Body73.new(number_type,
                 area_code,
                 quantity,
                 leftover)
    end
  end
end
