# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body53 Model.
  class Body53 < BaseModel
    # The type (category) of template Valid values: marketing, authorization
    # @return [String]
    attr_accessor :type

    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # The count of objects to return per page.
    # @return [Integer]
    attr_accessor :pagesize

    # Only list templates of type
    # @return [String]
    attr_accessor :shortcode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash['shortcode'] = 'Shortcode'
      @_hash
    end

    def initialize(type = nil,
                   page = nil,
                   pagesize = nil,
                   shortcode = nil)
      @type = type
      @page = page
      @pagesize = pagesize
      @shortcode = shortcode
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type']
      page = hash['page']
      pagesize = hash['pagesize']
      shortcode = hash['Shortcode']

      # Create object from extracted values.
      Body53.new(type,
                 page,
                 pagesize,
                 shortcode)
    end
  end
end
