# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body19 Model.
  class Body19 < BaseModel
    # A valid email address that is to be added to the unsubscribe list
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['email'] = 'email'
      @_hash
    end

    def initialize(email = nil)
      @email = email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash['email']

      # Create object from extracted values.
      Body19.new(email)
    end
  end
end
