# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Body62 Model.
  class Body62 < BaseModel
    # The page count to retrieve from the total results in the collection. Page
    # indexing starts at 1.
    # @return [Integer]
    attr_accessor :page

    # Number of individual resources listed in the response per page
    # @return [Integer]
    attr_accessor :pagesize

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['pagesize'] = 'pagesize'
      @_hash
    end

    def initialize(page = nil,
                   pagesize = nil)
      @page = page
      @pagesize = pagesize
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash['page']
      pagesize = hash['pagesize']

      # Create object from extracted values.
      Body62.new(page,
                 pagesize)
    end
  end
end
