# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # The leg of the call audio will be played to
  class Direction1Enum
    DIRECTION1_ENUM = [
      # TODO: Write general description for ENUM_IN
      ENUM_IN = 'in'.freeze,

      # TODO: Write general description for OUT
      OUT = 'out'.freeze,

      # TODO: Write general description for BOTH
      BOTH = 'both'.freeze
    ].freeze
  end
end
