# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Format of the recording file. Can be .mp3 or .wav
  class FileformatEnum
    FILEFORMAT_ENUM = [
      # TODO: Write general description for MP3
      MP3 = 'mp3'.freeze,

      # TODO: Write general description for WAV
      WAV = 'wav'.freeze
    ].freeze
  end
end
