# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # The capability the number supports.
  class NumberType2Enum
    NUMBER_TYPE2_ENUM = [
      # TODO: Write general description for ALL
      ALL = 'all'.freeze,

      # TODO: Write general description for VOICE
      VOICE = 'voice'.freeze,

      # TODO: Write general description for SMS
      SMS = 'sms'.freeze
    ].freeze
  end
end
