# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Number type either SMS,Voice or all
  class Numbertype1Enum
    NUMBERTYPE1_ENUM = [
      # TODO: Write general description for ALL
      ALL = 'all'.freeze,

      # TODO: Write general description for VOICE
      VOICE = 'voice'.freeze,

      # TODO: Write general description for SMS
      SMS = 'sms'.freeze
    ].freeze
  end
end
