# ytel_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Status to set the in-progress call to
  class Status1Enum
    STATUS1_ENUM = [
      # TODO: Write general description for CANCELED
      CANCELED = 'canceled'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze
    ].freeze
  end
end
